const countries = [
    { name: 'España', code: 'ES' },
    { name: 'Francia', code: 'FR' },
    { name: 'Alemania', code: 'DE' },
    { name: 'Italia', code: 'IT' },
    { name: 'Reino Unido', code: 'GB' },
    { name: 'Países Bajos', code: 'NL' },
    { name: 'Suiza', code: 'CH' },
    { name: 'Austria', code: 'AT' },
    { name: 'Bélgica', code: 'BE' },
    { name: 'Portugal', code: 'PT' },
    { name: 'Suecia', code: 'SE' },
    { name: 'Noruega', code: 'NO' },
    { name: 'Estados Unidos', code: 'US' },
    { name: 'Canadá', code: 'CA' },
    { name: 'México', code: 'MX' },
    { name: 'Brasil', code: 'BR' },
    { name: 'Argentina', code: 'AR' },
    { name: 'Colombia', code: 'CO' },
    { name: 'Chile', code: 'CL' },
    { name: 'Perú', code: 'PE' },
    { name: 'Venezuela', code: 'VE' },
    { name: 'Ecuador', code: 'EC' },
    { name: 'Costa Rica', code: 'CR' },
    { name: 'Panamá', code: 'PA' },
    { name: 'Mongolia', code: 'MN' },
    { name: 'China', code: 'CN' },
    { name: 'Kazajistán', code: 'KZ' },
    { name: 'Ucrania', code: 'UA' },
    { name: 'Bielorrusia', code: 'BY' },
    { name: 'Finlandia', code: 'FI' },
    { name: 'Estonia', code: 'EE' },
    { name: 'Irán', code: 'IR' },
    { name: 'Turquía', code: 'TR' },
    { name: 'Jordania', code: 'JO' },
    { name: 'Kuwait', code: 'KW' },
    { name: 'Arabia Saudita', code: 'SA' },
    { name: 'Siria', code: 'SY' },
    { name: 'Líbano', code: 'LB' },
    { name: 'Israel', code: 'IL' },
    { name: 'Jordania', code: 'JO' },
    { name: 'Arabia Saudita', code: 'SA' },
    { name: 'Sudán', code: 'SD' },
    { name: 'Libia', code: 'LY' },
]

export { countries }